### ISSUE TITLE
Errors when trying to use frozen strings

### ISSUE THREAD

**Issue by ioquatix** [flori/term-ansicolor#32]
```
FrozenError:
  can't modify frozen String
# /Users/samuel/.rvm/gems/ruby-2.5.1/gems/term-ansicolor-1.7.0/lib/term/ansicolor.rb:90:in `color'
# (eval):2:in `green'
# /Users/samuel/.rvm/gems/ruby-2.5.1/gems/coveralls-0.8.22/lib/coveralls/output.rb:67:in `block in format'
# /Users/samuel/.rvm/gems/ruby-2.5.1/gems/coveralls-0.8.22/lib/coveralls/output.rb:65:in `reverse_each'
# /Users/samuel/.rvm/gems/ruby-2.5.1/gems/coveralls-0.8.22/lib/coveralls/output.rb:65:in `format'
# /Users/samuel/.rvm/gems/ruby-2.5.1/gems/coveralls-0.8.22/lib/coveralls/output.rb:90:in `puts'
# /Users/samuel/.rvm/gems/ruby-2.5.1/gems/coveralls-0.8.22/lib/coveralls.rb:51:in `setup!'
# /Users/samuel/.rvm/gems/ruby-2.5.1/gems/coveralls-0.8.22/lib/coveralls.rb:18:in `wear!'
# ./spec/spec_helper.rb:4:in `<top (required)>'
# ./spec/timers/wait_spec.rb:3:in `require'
# ./spec/timers/wait_spec.rb:3:in `<top (required)>'
```

**Comment by ioquatix** [comment]
Bump :)
