### ISSUE TITLE
Release 1.9 - True Color adjustments causing crash for Ruby versions prior to 2.7 (OSX Ventura & Sonoma)

### ISSUE THREAD

**Issue by charlesbensonsonos** [flori/term-ansicolor#39]
https://github.com/flori/term-ansicolor/blame/ca864aee5db81a6bc26206a53864f8eec3f21caf/lib/term/ansicolor/attribute.rb#L98

```
[2024-06-20T15:22:32.846Z] bundler: failed to load command: pact-broker ((...)gems/ruby/2.6.0/bin/pact-broker)
[2024-06-20T15:22:32.846Z] NoMethodError: undefined method `start_with?' for :clear:Symbol
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute.rb:98:in `initialize'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute.rb:23:in `new'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute.rb:23:in `set'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute/text.rb:5:in `<class:Text>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute/text.rb:4:in `<class:Attribute>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute/text.rb:3:in `<module:ANSIColor>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute/text.rb:2:in `<module:Term>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor/attribute/text.rb:1:in `<top (required)>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor.rb:13:in `require'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor.rb:13:in `<module:ANSIColor>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor.rb:7:in `<module:Term>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/term-ansicolor-1.9.0/lib/term/ansicolor.rb:3:in `<top (required)>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/thor_unknown_options_monkey_patch.rb:2:in `require'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/thor_unknown_options_monkey_patch.rb:2:in `<top (required)>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/custom_thor.rb:2:in `require'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/custom_thor.rb:2:in `<top (required)>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/broker.rb:1:in `require'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/lib/pact_broker/client/cli/broker.rb:1:in `<top (required)>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/bin/pact-broker:2:in `require'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/gems/pact_broker-client-1.75.3/bin/pact-broker:2:in `<top (required)>'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/bin/pact-broker:23:in `load'
[2024-06-20T15:22:32.846Z]   (...)gems/ruby/2.6.0/bin/pact-broker:23:in `<top (required)>'
script returned exit code 1
```

MacOS Ventura & Sonoma releases from Apple still use Ruby 2.6 as their system ruby. 
start_with? support for symbol came out with Ruby 2.7.

Not saying this needs to be fixed, but just wanted to raise awareness that 1.9 breaks support for this older ruby thats included with MacOS Ventura. MacOS Sonoma is the latest release by Apple, however it too also ships with Ruby 2.6.
This means this package won't work on MacOS computers that are relying on the system installed Ruby to do work.

Wanted to raise awareness incase this should be fixed, and at the very least mark out that this is breaking because of MacOS system Ruby being at version 2.6 while this recent adjustment using start_with? on Symbol will only work on Ruby 2.7 and higher. 

Work arounds:
- Pin to ANSIColor version lower than 1.9
- Use brew or other methods to install a newer ruby, such as through rbenv or ruby-install

**Comment by flori** [comment]
Can you try this again with version `1.10.2`? I am not sure how to reproduce this, which command did you run?

**Comment by charlesbensonsonos** [comment]
line 98 - theres name.to_sym and then name.starts_with?

Symbols only support .starts_with? as of Ruby 2.7

The method was called via the Pact framework so not something I can control but the reference of the issue is to line 98 where a symbol has a method applied to it that only works in Ruby 2.7 and later

Repro steps should be
Have Ruby 2.6 set as your current ruby
Make a call into Attribute#initialize()
Observe exception

**Comment by flori** [comment]
> line 98 - theres name.to_sym and then name.starts_with?
> 
> Symbols only support .starts_with? as of Ruby 2.7

It seems so. The good news is that I removed this code in a subsequent release, so it should work in `1.10.2` if this was the only problem.

> The method was called via the Pact framework so not something I can control but the reference of the issue is to line 98 where a symbol has a method applied to it that only works in Ruby 2.7 and later

> Repro steps should be Have Ruby 2.6 set as your current ruby Make a call into Attribute#initialize() Observe exception

I have added testing on these old ruby version again, even though bundler doesn't like them very much (see https://github.com/flori/term-ansicolor/blob/b93f00905919b18401ecfbdc840a1ccb6566327d/.all_images.yml#L27) and the whole test suite is green for `2.6`.

> The fix is likely to use name.starts_with?("on_") instead of @name.starts_with?("on_")
> 
> I will test on Monday if this fixes it and if I run into anything else and will open a PR if needed and 1.10.2 doesn't help.

OK, IMO it should work now.
